version: '3'

services:
    mysql:
        image: mysql
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=password
        restart: unless-stopped
        ports:
            - "3306:3306"
        container_name: mysql
    redis:
        image: redis
        ports:
            - "6379:6379"
