version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
jobs:
  test_backend:
    docker:
      - image: circleci/node:10
      - image: circleci/mysql:8.0.18
        environment:
          MYSQL_ROOT_PASSWORD: password
      - image: circleci/python:3.6.2-stretch-browsers
    environment:
      DEFAULT_PICTURE: https://icon-library.net/icon/default-user-icon-14.html
      JWT_SECRET_KEY: Luan_7788$#
      CRYPRO_SECRET_KEY: MIma_@$
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run: npm run create_test_db
      # - run: npm test
      - run: pip install robotframework
      - run: pip install --upgrade robotframework-seleniumlibrary
      - run: npm run eeTest
      - run: npm run rbt_test
  migratedb:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: ./node_modules/.bin/sequelize db:migrate --env=production
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: master
     
workflows:
  test-build-deploy:
    jobs:
      - test_backend
      # - migratedb:
      #     requires:
      #       - test_backend
      # - deploy:
      #     requires: 
      #       - migratedb