PATCH http://localhost:3003/api/user/changePwd/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlck5hbWUiOiJ1c2VyMSIsInBpY3R1cmUiOiIvZGVmYXVsdGVkX3BpY3R1cmUuanBnIiwiaWF0IjoxNTgxNTAyMjM4LCJleHAiOjE1ODE1MDU4Mzh9.m0_V6HtQIoeDpfucIcTYpO-K6dd75AYUrvRSOb8bk1E

{
  "pwd": 123,
  "newPwd":456
}